### ISSUE TITLE
google gson error

### ISSUE THREAD

**Issue by Conor-Burns** [lucko/bytebin#1]
I am getting this error when running bytebin with your tutorial on selfhosting LuckyPerms webinterface
```
[20:42:05 ERROR]: Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 7 column 2 path $.maxContentLengthMb
[20:42:05 ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:942)
[20:42:05 ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:865)
[20:42:05 ERROR]: 	at me.lucko.bytebin.util.Configuration.load(Configuration.java:47)
[20:42:05 ERROR]: 	at me.lucko.bytebin.Bytebin.main(Bytebin.java:67)
[20:42:05 ERROR]: Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 7 column 2 path $.maxContentLengthMb
[20:42:05 ERROR]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
[20:42:05 ERROR]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:505)
[20:42:05 ERROR]: 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
[20:42:05 ERROR]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
[20:42:05 ERROR]: 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
[20:42:05 ERROR]: 	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:894)
[20:42:05 ERROR]: 	at com.google.gson.Gson.fromJson(Gson.java:927)
[20:42:05 ERROR]: 	... 3 more

```

**Comment by lucko** [comment]
Your configuration file is formatted incorrectly - not a bytebin bug :)

**Comment by Conor-Burns** [comment]
I copied it from the example and just changed the port

**Comment by Conor-Burns** [comment]
Ah got it the last , is not needed
