### ISSUE TITLE
Insufficient configured threads after switch to jetty

### ISSUE THREAD

**Issue by Derkades** [lucko/bytebin#17]
```
[13:17:04 INFO]: loading bytebin...
[13:17:04 INFO]: Logging initialized @891ms to org.eclipse.jetty.util.log.Slf4jLog
[13:17:04 INFO]: jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.2+8-alpine-r0
[13:17:04 INFO]: Started o.e.j.s.h.ContextHandler@439a8f59{/,null,AVAILABLE}
[13:17:04 INFO]: ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0} requires 1 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:04 INFO]: ServerConnector@2e54db99{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} requires 2 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:04 INFO]: SelectorManager@ServerConnector@2e54db99{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} requires 1 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:06 INFO]: loading bytebin...
[13:17:06 INFO]: Logging initialized @910ms to org.eclipse.jetty.util.log.Slf4jLog
[13:17:06 INFO]: jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 17.0.2+8-alpine-r0
[13:17:06 INFO]: Started o.e.j.s.h.ContextHandler@439a8f59{/,null,AVAILABLE}
[13:17:06 INFO]: ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0} requires 1 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:06 INFO]: ServerConnector@2e54db99{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} requires 2 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:06 INFO]: SelectorManager@ServerConnector@2e54db99{HTTP/1.1, (http/1.1)}{0.0.0.0:8080} requires 1 threads from QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:06 ERROR]: Application startup resulted in exception
java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
     at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:165) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:141) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:191) ~[bytebin.jar:?]
     at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:255) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110) ~[bytebin.jar:?]
     at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321) ~[bytebin.jar:?]
     at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81) ~[bytebin.jar:?]
     at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[bytebin.jar:?]
     at org.eclipse.jetty.server.Server.doStart(Server.java:401) ~[bytebin.jar:?]
     at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73) ~[bytebin.jar:?]
     at io.jooby.jetty.Jetty.start(Jetty.java:204) ~[bytebin.jar:?]
     at io.jooby.Jooby.start(Jooby.java:802) ~[bytebin.jar:?]
     at me.lucko.bytebin.Bytebin.<init>(Bytebin.java:147) ~[bytebin.jar:?]
     at me.lucko.bytebin.Bytebin.main(Bytebin.java:77) ~[bytebin.jar:?]
[13:17:06 INFO]: Stopped BytebinServer
[13:17:06 INFO]: Stopped ServerConnector@2e54db99{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
[13:17:06 INFO]: Stopped o.e.j.s.h.ContextHandler@439a8f59{/,null,STOPPED}
[13:17:06 ERROR]: Exception in thread "main" io.jooby.exception.StartupException: Application startup resulted in exception
[13:17:06 ERROR]:    at io.jooby.Jooby.start(Jooby.java:812)
[13:17:06 ERROR]:    at me.lucko.bytebin.Bytebin.<init>(Bytebin.java:147)
[13:17:06 ERROR]:    at me.lucko.bytebin.Bytebin.main(Bytebin.java:77)
[13:17:06 ERROR]: Caused by: java.lang.IllegalStateException: Insufficient configured threads: required=4 < max=4 for QueuedThreadPool[worker]@1338fb5{STARTED,4<=4<=4,i=4,r=-1,q=0}[ReservedThreadExecutor@2c177f9e{reserved=0/1,pending=0}]
[13:17:06 ERROR]:    at org.eclipse.jetty.util.thread.ThreadPoolBudget.check(ThreadPoolBudget.java:165)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseTo(ThreadPoolBudget.java:141)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.thread.ThreadPoolBudget.leaseFrom(ThreadPoolBudget.java:191)
[13:17:06 ERROR]:    at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:255)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
[13:17:06 ERROR]:    at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:321)
[13:17:06 ERROR]:    at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
[13:17:06 ERROR]:    at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
[13:17:06 ERROR]:    at org.eclipse.jetty.server.Server.doStart(Server.java:401)
[13:17:06 ERROR]:    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
[13:17:06 ERROR]:    at io.jooby.jetty.Jetty.start(Jetty.java:204)
[13:17:06 ERROR]:    at io.jooby.Jooby.start(Jooby.java:802)
[13:17:06 ERROR]:    ... 2 more
```
My docker-compose:
```yaml
  bytebin:
    image: ghcr.io/lucko/bytebin
    read_only: true
    networks: [proxy]
    user: '1000'
    cap_drop: ['ALL']
    volumes:
      - type: bind
        source: ./bytebin
        target: /opt/bytebin/content
      - type: bind
        source: ./log4j2.xml
        target: /opt/bytebin/log4j2.xml
        read_only: true
      - type: tmpfs
        target: /opt/bytebin/tmp
        tmpfs:
          size: 50M
    environment:
      BYTEBIN_MISC_KEYLENGTH: 10
      BYTEBIN_CONTENT_MAXSIZE: 5
      BYTEBIN_LOG4J_CONFIG: /opt/bytebin/log4j2.xml
      BYTEBIN_CACHE_MAXSIZE: 0
    restart: always
```

**Comment by lucko** [comment]
Thanks for reporting, that should do the trick.

**Comment by Derkades** [comment]
Yep it's fixed, thanks
